version: "3.9"
services:
  db:
    container_name: db-bookstore
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - db-bookstore:/data/db

  redis:
    container_name: redis-bookstore
    image: redis:alpine3.18
    ports:
      - 6379:6379

volumes:
  db-bookstore: