version: "3.9"
services:
  db:
    container_name: db-bookstore
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - db-bookstore:/data/db

volumes:
  db-bookstore: